apiVersion: v1
kind: Service
metadata:
  name: example-service1
  namespace: demo-yaml
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-service1
  type: ClusterIP
