apiVersion: v1
kind: Service
metadata:
  name: example-service2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: example-service2
  type: ClusterIP
