apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: example-service2
  name: example-service2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: example-service2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: example-service2
    spec:
      containers:
      - image: soloio/example-service2:v0.2.2
        name: example-service2
        ports:
        - containerPort: 8080
        resources: {}
status: {}
