apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: example-service1
  name: example-service1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: example-service1
  type: ClusterIP
status:
  loadBalancer: {}
